image: alpine:3.10

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SSH_GITLAB_KEY: $SSH_PRIVATE_KEY
  IMAGE_NAME: $CI_PUBLIC_REGISTRY/official_images/bash
  BUSTER_IMAGE_TAG: buster-slim

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - /var/cache/apk

stages:
  - test
  - build

before_script:
  - apk add -U openssh-client git make alpine-sdk
  - REPOSITORY_PATH=${CI_PROJECT_URL#*//}
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - echo "${SSH_GITLAB_KEY}" > /root/.ssh/id_rsa
  - chmod 600 /root/.ssh/id_rsa
  - ssh-keyscan git.cto.ai > /root/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null" > ~/.ssh/config
  - git config --global url."ssh://git@git.cto.ai:2224".insteadOf "https://git.cto.ai"

after_script:
  - rm -rf /root/.ssh

version:
  stage: test
  image: alpine:3.11.3
  except:
    - master
  before_script:
    - echo Begin check on incremented version in Cargo.toml
  script:
    - apk update && apk add git
    - export CURRENT_VERSION=$(cat Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && echo "${value}"&& break; done)
    - export MASTER_VERSION=$(git fetch && git --no-pager show origin/master:Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && echo "${value}" && break; done)
    - echo -e "current is $CURRENT_VERSION\nmaster is $MASTER_VERSION"
    - sh -c '[ "$1" != "$(echo -e "$1\n$2" | sort -V | head -n1)" ] && exit 0' sh "${CURRENT_VERSION}" "${MASTER_VERSION}"
  after_script:
    - echo Done

# Build stage for branches other than master (based on tag)
build-branch:
  stage: build
  image: docker:stable
  only:
    - tags
  except:
    - master
  script:
    - export CURRENT_VERSION=$(Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && temp="${value%\"}" && echo "${temp#\"}" && break; done)
    - docker login -u $PUBLIC_CI_USER -p $PUBLIC_CI_TOKEN $CI_PUBLIC_REGISTRY
    - docker build --build-arg SSH_GITLAB_KEY="$(cat ~/.ssh/id_rsa)" -t $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG .
    - docker push $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG

# Build stage for the master branch (automatic)
build-master:
  stage: build
  only:
    - master
  image: docker:stable
  script:
    - export CURRENT_VERSION=$(cat Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && temp="${value%\"}" && echo "${temp#\"}" && break; done)
    - export CURRENT_MAJOR_VERSION="${CURRENT_VERSION%%.*}"
    - export CURRENT_MAJOR_MINOR_VERSION="${CURRENT_VERSION%.*}"
    - docker login -u $PUBLIC_CI_USER -p $PUBLIC_CI_TOKEN $CI_PUBLIC_REGISTRY
    - docker build --build-arg SSH_GITLAB_KEY="$(cat ~/.ssh/id_rsa)" -t $IMAGE_NAME:latest .
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_MAJOR_VERSION-$BUSTER_IMAGE_TAG
    - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_MAJOR_MINOR_VERSION-$BUSTER_IMAGE_TAG
    - docker push $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG
    - docker push $IMAGE_NAME:$CURRENT_MAJOR_VERSION-$BUSTER_IMAGE_TAG
    - docker push $IMAGE_NAME:$CURRENT_MAJOR_MINOR_VERSION-$BUSTER_IMAGE_TAG
