[package]
name = "bash-sdk"
version = "2.3.0"
authors = ["Danielle Brook-Roberge <danielle@cto.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]

[dependencies]
commands = { path = "commands" }
clap = "2.33.0"
