
name: Integration Tests
on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: 'Tag version (e. 1.1.6)'
        required: true

env:
  CI_USER: ${{ secrets.CI_USER }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
    - name: Clone integration tests
      run: |
        git clone https://${{ secrets.CTO_PAT }}@github.com/cto-ai/sdk-integration-testing.git
    - name: Docker Build
      run: |
        docker build -t bash-test --build-arg SDK_VERSION=${{github.event.inputs.gitTag}} -f sdk-integration-testing/Dockerfile.bash sdk-integration-testing
        docker run --rm bash-test
