name: Build & Release
on:
  workflow_dispatch:
  
env:
  DOCKER_DRIVER: overlay
  SSH_GITLAB_KEY: $SSH_PRIVATE_KEY
  IMAGE_NAME: $CI_PUBLIC_REGISTRY/official_images/bash
  BUSTER_IMAGE_TAG: buster-slim

jobs:
  test:
    runs-on: alpine:3.10
    steps:
      - uses: actions/checkout@v2
      
      - name: Before Script
        run: apk add -U openssh-client git make alpine-sdk
      - name: Version
        run: |
          - apk update && apk add git
          - export CURRENT_VERSION=$(cat Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && echo "${value}"&& break; done)
          - export MASTER_VERSION=$(git fetch && git --no-pager show origin/master:Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && echo "${value}" && break; done)
          - echo -e "current is $CURRENT_VERSION\nmaster is $MASTER_VERSION"
          - sh -c '[ "$1" != "$(echo -e "$1\n$2" | sort -V | head -n1)" ] && exit 0' sh "${CURRENT_VERSION}" "${MASTER_VERSION}"
          
  build:
    runs-on: docker:stable
    needs: test
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Branch
        run: |
          - export CURRENT_VERSION=$(Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && temp="${value%\"}" && echo "${temp#\"}" && break; done)
          - docker login -u $PUBLIC_CI_USER -p $PUBLIC_CI_TOKEN $CI_PUBLIC_REGISTRY
          - docker build --build-arg SSH_GITLAB_KEY="$(cat ~/.ssh/id_rsa)" -t $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG .
          - docker push $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG
      - name: Build Master
        run: |
          - export CURRENT_VERSION=$(cat Cargo.toml | while IFS=" = " read -r name value; do [ "${name}" == "version" ] && temp="${value%\"}" && echo "${temp#\"}" && break; done)
          - export CURRENT_MAJOR_VERSION="${CURRENT_VERSION%%.*}"
          - export CURRENT_MAJOR_MINOR_VERSION="${CURRENT_VERSION%.*}"
          - docker login -u $PUBLIC_CI_USER -p $PUBLIC_CI_TOKEN $CI_PUBLIC_REGISTRY
          - docker build --build-arg SSH_GITLAB_KEY="$(cat ~/.ssh/id_rsa)" -t $IMAGE_NAME:latest .
          - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG
          - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_MAJOR_VERSION-$BUSTER_IMAGE_TAG
          - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CURRENT_MAJOR_MINOR_VERSION-$BUSTER_IMAGE_TAG
          - docker images
          # - docker push $IMAGE_NAME:latest
          # - docker push $IMAGE_NAME:$CURRENT_VERSION-$BUSTER_IMAGE_TAG
          # - docker push $IMAGE_NAME:$CURRENT_MAJOR_VERSION-$BUSTER_IMAGE_TAG
          # - docker push $IMAGE_NAME:$CURRENT_MAJOR_MINOR_VERSION-$BUSTER_IMAGE_TAGz
