name: Continuous integration
on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target chipset arch list'
        default: 'amd64'
        type: choice
        options:
        - amd64
        - arm64
        - amd64,arm64
  push:
    tags-ignore:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.72
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy
      - name: Test
        run: |
          cargo test

  build:
    needs: test
    uses: ./.github/workflows/wc_build_binaries.yml
    with:
      arch: ${{ inputs.arch }}
      artifact_retention: 1
