name: Continuous integration
on:
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target chipset arch list'
        default: 'amd64'
        type: choice
        options:
        - amd64
        - arm64
        - amd64,arm64
  push:
    branches-ignore:
      - master

env:
  DOCKER_DRIVER: overlay
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  GH_TOKEN: ${{ secrets.CTO_PAT }}

jobs:
  test:
    runs-on: ubuntu-latest
    container: rust:1.62
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          git config --global url.'https://${{ secrets.CTO_PAT }}@github.com/cto-ai'.insteadOf 'https://github.com/cto-ai'
          git config --global url.'https://${{ secrets.CTO_PAT }}@github.com'.insteadOf 'ssh://git@github.com'
      - name: Lint
        run: |
          rustup component add clippy
          cargo clippy
      - name: Test
        run: |
          cargo test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          ./scripts/build-setup
      - name: Build
        run: |
          ./scripts/build ${{ github.event.inputs.arch }}
      - name: Package
        run: |
          ./scripts/package
      - name: Publish
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          path: |
            dist/**/*
            !dist/*.tar.gz
