name: Release
on:
  push:
    tags:
      - "v*"
  # Workflow dispatch should be used only as fallback method
  workflow_dispatch:
    inputs:
      version:
        description: 'version to be released'
        required: true
      arch:
        description: 'Target chipset arch list'
        default: 'amd64,arm64'
        type: choice
        options:
        - amd64
        - arm64
        - amd64,arm64

env:
  DOCKER_DRIVER: overlay
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          VERSION_IN_CARGO=$(find . -type f -name 'Cargo.toml' -exec grep -oP '^\W*version\W*\K[0-9\.]+' {} \; | sort -nru | head -1)
          GIT_TAG='${{ github.ref_name }}'

          if [ "${GIT_TAG/#v/}" != "${VERSION_IN_CARGO}" ]; then
            echo 'git tag and Cargo.toml version mismatch'
            echo "${GIT_TAG/#v/} != ${VERSION_IN_CARGO}"
            echo ''
            echo 'REMINDER: Git tags must start with "v"'
            exit 1
          fi
      - name: Setup
        run: |
          ./scripts/build-setup
      - name: Build
        run: |
          ./scripts/build ${{ inputs.arch }}
      - name: Package
        run: |
          ./scripts/package
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: package
          retention-days: 7
          path: dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch packaged artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
