name: Release
on:
  # Remember to select a Git tag otherwise the workflow will fail
  workflow_dispatch:
    inputs:
      arch:
        description: 'Target chipset arch list'
        default: 'amd64,arm64'
        type: choice
        options:
        - amd64
        - arm64
        - amd64,arm64

env:
  DOCKER_DRIVER: overlay
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version
        run: |
          VERSION_IN_CARGO=$(find . -type f -name 'Cargo.toml' -exec grep -oP '^\W*version\W*\K[0-9\.\-rc]+' {} \; | sort -nru | head -1)
          GIT_TAG='${{ github.ref_name }}'

          if [[ "${GIT_TAG/#v/}" != "${VERSION_IN_CARGO}" ]]; then
            echo 'Version mismatch between git tag and Cargo.toml'
              echo "git:   ${GIT_TAG/#v/}"
              echo "cargo: ${VERSION_IN_CARGO}"
            echo ''
            echo 'REMINDERS:'
            echo '  - This workflow must be triggered from a Git tag'
            echo '  - Git tags must start with "v"'
            exit 1
          fi
        shell: bash

  build:
    needs: check
    uses: ./.github/workflows/wc_build_binaries.yml
    with:
      arch: ${{ inputs.arch }}
      artifact_retention: 7

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Fetch packaged artifacts
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            dist/*.tar.gz
